"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

def n_fibonacci(n):
	if(n == 1):
		return 1
	elif(n == 2):
		return 2
	return n_fibonacci(n - 1) + n_fibonacci(n - 2)

def main():
	i = 1
	j = 0

	while(n_fibonacci(i) < 4000000):
		n = n_fibonacci(i)
		if(n % 2 == 0):
			j += n
		i += 1

	print(f"The sum of the even-valued terms is {j}")


if __name__ == '__main__':
	main()